carekit-apple/CareKit

- docs/AccessingCarePlanData/AccessingCarePlanData-template.md
- docs/ConnectingWithCareTeamsAndPersonalContacts/ConnectingWithCareTeamsAndPersonalContacts-template.md
- docs/CreatingTheCareCard/CreatingTheCareCard-template.md
- docs/CreatingTheSymptomAndMeasurementTracker/CreatingTheSymptomAndMeasurementTracker-template.md
- docs/PresentingInsights/PresentingInsights-template.md
Unify code blocks of documents.
Summary:
1. replace tab-based code blocks with backtick ones (fenced code blocks)
2. add syntax highlighting for Swift and Objective-C
3. unify whitespace and indentions in code blocks
4. remove trailing whitespace
> Unify code blocks.

- docs/AccessingCarePlanData/AccessingCarePlanData-template.md
Hi all,
I converted some example code to Swift in #14.
However, some characters is not displaying correctly due to a bug made by me 😭 
We'd like to display `°F` and `°C` on the screen, but I put the `C` and `F` into the hexadecimal block the the text was rendered as  `ଏ` (0B0F) and `ଌ` (0B0C).
I've fixed this. Really sorry about the bug :bow:
It would be appreciated if you could take some time reviewing the changes.
> [Dcumentation] Fix misplaced unicode chars "\u{0B0C}" and "\u{0B0F}"

- CareKit/CareCard/OCKCareCardWeekView.m
- CareKit/CareCard/OCKHeartButton.m
- CareKit/SymptomTracker/OCKSymptomTrackerWeekView.m
I increased the size of the buttons for the week view in the Care Card and Symptom Tracker so that you can tap on the day of the week label to change the day as well as by tapping the circle or heart underneath. This doesn't change anything visually.
> Increased tap target size in week view control.

- docs/Overview/Overview-template.md
Remove trailing `.` characters in image descriptions, causing new lines and isolated characters when rendered in HTML.
> Remove superfluous characters

- CareKit/Connect/OCKConnectTableViewCell.m
- CareKit/Connect/OCKConnectTableViewHeader.m
- CareKit/Connect/OCKContact.h
- CareKit/Connect/OCKContact.m
When an emoji is used in monogram label in the connect TVC sometimes the monogram becomes truncated. Turning on adjustsFontSizeToFitWidth is a quick fix but other fixes may be desired. I believe the phone and contacts apps on iOS display a default avatar image when an emoji is the first character in a contact's first or last name. An emoji might be a silly example but other unicode glyphs could become truncated as well. See the before and after images.
> Fix connect cell monogram truncation

- CareKit/SymptomTracker/OCKSymptomTrackerViewController.m
Hi there,
I noticed that ``OCKSymptomTrackerViewController`` doesn't update its contents when activity list is changed. According to ``handleActivityListChange`` in ``OCKCarePlanStore``,
I guess ``carePlanStoreActivityListDidChange`` should be correct method name
by original intention.
Cheers,
> OCKSymptomTrackerViewController doesn't update contents when activity list is changed

- CareKit.podspec
- CareKit/Utilities/OCKHelpers.h
- CareKit/Utilities/OCKHelpers.m
- testing/OCKTest/OCKTest/MainTableViewController.h
Podspec file + changes needed to build OCKTest and CareKit for the simulator via CocoaPods.
This was requested via #1 .
> CareKit CocoaPods support

- CareKit/CarePlan/OCKCarePlanStore.m
Previously, the callback would contain `YES` and an error. Now, it properly returns `NO` and an error. I also tried to clarify the semantics to avoid future confusion, at the expense of a bit of verbosity.
As a side note, the naming here makes it very easy to get confused, which it seems is what happened to both the original implementer and to me when I reported #37. I might prefer calling the `error` parameter `errorPtr` or similar, but didn't make that change here as the same convention is used throughout the class.
> Fix store callback when an activity with an existing identifier is added

- CareKit/CareCard/OCKCareCardTableViewCell.m
If an intervention activity had 7 events scheduled for a single day, the bottom constraints for the event circles weren't being constructed.
> Fix constraints for 7/day schedule in CareCardCell

- CareKit/CareCard/OCKCareCardTableViewHeader.h
- CareKit/CareCard/OCKCareCardTableViewHeader.m
- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/Connect/OCKConnectDetailViewController.m
- CareKit/Connect/OCKConnectViewController.h
- CareKit/Connect/OCKConnectViewController.m
- Sample/OCKSample/RootViewController.swift
- testing/OCKTest/OCKTest/ConnectTableViewController.swift
This adds peek and pop functionality to `OCKCareCardViewController` and `OCKConnectViewController`. When applying pressure to the table view cells, the peek view will show the respective detail view controller.
`OCKConnectDetailViewController` now leverages preview action items. When peeking into an `OCKConnectDetailViewController` from an `OCKConnectViewController`, swiping up will provide options to call, text, email, or send reports to the contact. Only the available options will be shown.
In order to do this, I added `UIViewControllerPreviewingDelegate` to `OCKCareCardViewController` and `OCKConnectViewController`. I implemented the `previewActionItems` method on `OCKConnectDetailViewController` to show the peek options.
To prevent a weird animation from occurring when applying …
> Add 3D Touch to Care Card and Connect

- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/Connect/OCKConnectDetailViewController.m
- CareKit/Connect/OCKConnectViewController.m
I noticed that unlike other Apple apps, my 3D Touch implementation didn't "bounce" after popping. After further investigation, I found that the culprit was reinitializing the view controller again to pop. This PR fixes that.
I also added the copyright info I forgot to add in my previous PR (#78).
> 3D Touch Optimization

- CareKit.xcodeproj/project.pbxproj
- CareKit/CareKit.h
Moves OCKCareCardDetailViewController.h from a private header to a public one, and includes it in CareKit.h.
This allows users to subclass the detail view controller to customize it. By implementing the `OCKCareCardViewControllerDelegate` method `func careCardViewController(_ viewController:didSelectRowWithInterventionActivity:)`, a user can then push their custom subclass of the detail view controller.
I've found it to be a nice way to add extra table view sections. One trick I still had to use was exposing the `sectionTitles` property:
```
var sectionTitles: [String] {
get { return value(forKey: "_sectionTitles") as! [String] }
set { setValue(newValue, forKey: "_sectionTitles") }
}
```
Then I could append my own sections in `viewDidLoad` and override the table view data source methods …
> Make OCKCareCardDetailViewController public

- CareKit/CareCard/OCKCareCardTableViewHeader.h
- CareKit/CareCard/OCKCareCardTableViewHeader.m
- CareKit/CareCard/OCKCareCardViewController.h
- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/SymptomTracker/OCKSymptomTrackerTableViewHeader.h
- CareKit/SymptomTracker/OCKSymptomTrackerTableViewHeader.m
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.h
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.m
There are use cases that the default header titles for Care Card and Symptom Tracker, i.e. "Care Completion" and "Activity Completion," respectively, cannot provide clear instructions to users. This PR allows customizing the header title by setting the ```headerTitle``` of the corresponding ```OCKCareCardViewController``` or ```OCKSymptomTrackerViewController``` instance.
> Allow custom header title in Care Card and Symptom Tracker

- CareKit/Connect/OCKConnectViewController.m
This fixes #34 . Similar issue seems to persist in `OCKWeekViewController`.
> Avoid calling self.view if view has not been loaded

- CareKit.xcodeproj/project.pbxproj
- CareKit/CareCard/OCKCareCardViewController.h
- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/Connect/OCKConnectViewController.h
- CareKit/Connect/OCKConnectViewController.m
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.h
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.m
I'm working on a project in which I'd like to add a custom `tableViewHeader` to some of the table views in CareKit, but there is no public accessors currently.
The workaround I'm currently using is to filter subviews for a `UITableView`, but this is not really an ideal solution, so I decided to create a pull request to make the tableView property on `OCKCareCardViewController`, `OCKConnectViewController`, and `OCKSymptomTrackerViewController` available publicly.
> Public access to table view properties

- Sample/OCKSampleWatch Extension/ComplicationController.swift
Error:
'CLKComplicationTemplateExtraLargeStackImage' is only available on watchOS application extension 3.0 or newer
> Fix Xcode 8.3 error about watch API availability

- Sample/OCKSample/QueryActivityEventsOperation.swift
This removes the comments referencing <rdar://problem/25528295>. It also moves the query off the main thread since it no longer needs to be there. No longer necessary `self.` statements are also removed.
This will probably close #134
> Update QueryActivityOperation now that threading bug is fixed

- CareKit/Insights/OCKInsightsTableViewHeaderView.m
Fix for #177 - reduce the priority of OCKInsightsTableViewHeaderView's internal height constraint to 999, so any owner of this header view can set its height with higher priority.
> Fix for issue 177 - OCKInsightsTableViewHeaderView conflicting constraints

- CareKit/CarePlan/OCKCareSchedule.m
The `UTC_calendar` property on `OCKCareSchedule` is initialized
and configured lazily on first access inside a getter. This operation
is not atomic. Because the framework may call schedule methods on
different threads (for example, some operations are on
the OCKCarePlan serial), this can create a race condition.
To resolve this issue, we synchronizing the lazy initialization on
the instance itself. This resolved crashes we'd been seeing related
to this property.
> Synchronize Lazy Instantiation of Schedule Calendar

- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/Common/OCKHeaderView.m
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.m
This addresses issue #182.
Starting in CK 1.2 the following localization strings are no longer used:
- CARE_CARD_HEADER_TITLE
- SYMPTOM_TRACKER_HEADER_TITLE
They have now been replaced by the following:
- HEADER_TITLE_CARE_OVERVIEW
- HEADER_TITLE_ACTIVITY_STATUS
> Fix for displaying custom headerTitle when set

- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/CareContents/OCKCareContentsViewController.m
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.m
Prior to CK 1.2, navigating to future date in Care Card and Symptom Tracker is prevented.  In CK 1.2 this was broken.  This PR fixes the issue.
> Fix to prevent navigating to future dates in the Care Card, Symptom Tracker, and Care Contents views

- CareKit/CareCard/OCKCareCardViewController.h
- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/CareContents/OCKCareContentsViewController.h
- CareKit/CareContents/OCKCareContentsViewController.m
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.h
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.m
Adds functionality which allows developers to support pull to refresh style behavior in their CareKit apps. The delegates of each of the three activity-listing view controllers now include methods which allow the developer to enable pull to refresh and to perform a custom action when refreshing is triggered by the user.
This is especially useful for developers leveraging the bridge API's to connect their CareKit apps to a cloud backend and synchronize data across account logins or sessions.
> Allow developers to enable pull to refresh on activity listing view controllers

- CareKit/CarePlan/NSDateComponents+CarePlan.m
Similar to fixed PR #169, this commit synchronizes the lazy instantiation of the UTC_gregorianCalendar to avoid crashes due to race conditions.
> Synchronize lazy instantiation of UTC_gregorianCalendar

- CareKit.xcodeproj/xcshareddata/xcschemes/CareKit.xcscheme
I believe this addresses the issue in #172 and allows building with [Carthage](https://github.com/Carthage/Carthage/).
Here is a sample project you can use to test this functionality.
[CareKitDemo.zip](https://github.com/carekit-apple/CareKit/files/1609338/CareKitDemo.zip)
Download the sample project. In terminal change to the demo project's root directory and run `carthage bootstrap`. The output in your terminal should look similar to this:
```
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Cloning CareKit
*** Checking out CareKit at "b38ebd184a29313304adf08fcb5a1422eb2de4cf"
*** xcodebuild output can be found in /var/folders/t7/4ql0gqm55_z8dl5f7kk2g3h00000gn/T/carthage-xcodebuild.FlMXMa.log
*** Building scheme "CareKit" in CKWorkspace.xcworkspace
```
You …
> Share CareKit framework scheme

- CareKit/CareCard/OCKCareCardViewController.h
- CareKit/CareCard/OCKCareCardViewController.m
- CareKit/CareContents/OCKCareContentsViewController.h
- CareKit/CareContents/OCKCareContentsViewController.m
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.h
- CareKit/SymptomTracker/OCKSymptomTrackerViewController.m
- Sample/OCKSample/RootViewController.swift
This is a continuation of #155. The original pull request fell too far behind the master and rebasing became unwieldy, so the decision was made to resubmit the PR on a fresh branch.
I also made some minor changes to styling to make it match the rest of CareKit better. The `UILabel`s have been swapped out for `OCKLabel`s and the styling has been changed to match the `_noContactsLabel` from the OCKConnectViewController.
I've also fixed a bug in which the label hid under the header by adjusting the autoresizing mask, and another bug in which the `noEventsText` was not being updated in its setter method. Changes were tested in the CareKit sample app by replacing the sample data activities with an empty array. 
Touching the empty table view causes the app to crash, but this is a pre-existing …
> Optional empty message

- CareKit/CarePlan/OCKCarePlanEvent.h
Should be `event` instead of `activity`
> Fix documentation comment error

- CareKit/CareKit/Synchronized View Controllers/Synchronization/OCKSynchronizedStoreManager+Publishers.swift
The name spacing in Combine changed in the latest Xcode beta. 
`Publishers.Future` became just `Future`. This PR addresses the change and makes it possible to build CareKit 2.0 on Xcode 11 beta 3.
> Resolve breaking API changes in Combine from Xcode 11 beta 3

- CareKit/CareKit/Lists/View/OCKHeaderBodyView.swift
- CareKit/CareKit/Lists/View/OCKListView.swift
- CareKitUI/CareKitUI/Common/Extensions/UIFont+Extensions.swift
- CareKitUI/CareKitUI/Common/Views/OCKCollapsedView.swift
- CareKitUI/CareKitUI/Common/Views/OCKSeparatorView.swift
- CareKitUI/CareKitUI/Components/Task/Buttons/OCKLabeledCircleButton.swift
- CareKitUI/CareKitUI/Components/Task/Buttons/OCKLogItemButton.swift
- CareKitUI/CareKitUI/Components/Task/OCKChecklistTaskView.swift
- CareKitUI/CareKitUI/Components/Task/OCKInstructionsTaskView.swift
- CareKitUI/CareKitUI/Components/Task/OCKSimpleLogTaskView.swift
- CareKitUI/CareKitUI/Components/Task/OCKSimpleTaskView.swift
- CareKitUI/CareKitUI/Detail View/OCKDetailView.swift
Just wanted to contribute a few fixes and updates for issues I noticed:
- Reorders method declarations in custom `UIView`s to match their corresponding `setup()` methods. Matching the call order improves readability and makes parsing much quicker.
- Fixes numerous typos.
- Adds missing `MARK`s.
- Adds consistent messaging for `fatalError(...)` in `OCKHeaderBodyView`.
> Fix typos and update code formatting

- .travis.yml
- CareKit/CareKit.xcodeproj/xcshareddata/xcschemes/CareKit.xcscheme
- CareKitStore/CareKitStoreTests/Store/TestStore+Tasks.swift
This PR enables TravisCI for CareKit 2.0
Note that running tests for CareKit now also runs tests for CareKitUI and CareKitStore.
> Integrate TravisCI for CareKit 2.0

- OCKCatalog/OCKCatalog/AppDelegate.swift
- OCKCatalog/OCKCatalog/RootViewController.swift
- OCKCatalog/OCKCatalog/SceneDelegate.swift
- OCKSample/OCKSample/AppDelegate.swift
- OCKSample/OCKSample/SceneDelegate.swift
We do not want to create or keep the store in the scene delegate. If the app supports multiple windows (new in iOS 13) a new scene delegate will be instantiated for every window, which means a new store would be created too. We want to share the store across windows, so it should go in the app delegate. This updates the sample app to reflect best practices.
> Move store manager

- CareKitStore/CareKitStore/Structs/OCKHealthKitLinkage.swift
There was some confusion because `OCKHealthKitLinkage` was a public type, but there are not public APIs that consume it. This PR marks it internal to rectify that discrepancy.
> Mark OCKHealthKitLinkage internal

- CareKitStore/CareKitStore/CoreData/OCKCDOutcome.swift
- CareKitStore/CareKitStore/CoreData/OCKManagedObjectModel.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift
- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataTaskStore.swift
- CareKitStore/CareKitStore/Protocols/Events/OCKEventStore.swift
- CareKitStore/CareKitStoreTests/CoreDataSchema/TestCoreDataSchema+Outcomes.swift
- CareKitStore/CareKitStoreTests/CoreDataSchema/TestCoreDataSchemaIntegration.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Outcomes.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Tasks.swift
These changes modify the behavior of versioned tasks and fix #349.
1. Avoid a hard crash if a later version of a task has an earlier `effectiveDate` than a previous version.
2. Assure that outcomes can't be added to "shadowed" areas of past versions of tasks.
Consider the following case.
```
|--------- Query Interval ------------|
Task V1 -------------------------->
V2 ----------------->
V3----------------------->
```
When querying for events in the given interval, we start from version three and gather all outcomes. We then move on to version 2 and gather all outcomes in the region before V3 begins. A crash would occur in this case because there the time between the start of V2 and V3 is negative.
**This was fixed by skipping over versions that are fully shadowed**. Unit tests have been …
> Fix crash caused by updating a task without changing its effective date

- CareKitStore/CareKitStore/Structs/OCKSchedule.swift
- CareKitStore/CareKitStore/Structs/OCKScheduleElement.swift
- CareKitStore/CareKitStoreTests/Structs/TestSchedule.swift
This change addresses a bug in which tasks with a duration of `.allDay` were not properly captured by `OCKSchedule`'s `events(from:to:)` method.
```swift
let morning = Calendar.current.startOfDay(for: Date())
let breakfast = Calendar.current.date(byAdding: .hour, value: 7, to: morning)!
let lunch = Calendar.current.date(byAdding: .hour, value: 12, to: morning)!
let dinner = Calendar.current.date(byAdding: .hour, value: 18, to: morning)!
let allDay = OCKScheduleElement(start: breakfast, end: nil, interval: DateComponents(day: 1), text: "Daily", duration: .allDay)
let schedule = OCKSchedule(composing: [allDay])
// This should return 1 event. It was incorrectly returning 0.
let events = schedule.events(from: lunch, to: dinner)
```
> Fix a bug that involved scheduling of all day tasks

- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataTaskStore.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Tasks.swift
This is a fix for the bug discovered in by #353.
There was a logical error in the pre-update validation for tasks.
A unit test has been added to cover this case.
> Fix for a bug that prevented tasks with outcomes from being updated.

- CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Contacts.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift
- CareKitStore/CareKitStore/CoreData/OCKStore.swift
- CareKitStore/CareKitStore/Protocols/OCKObjectCompatible.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Outcomes.swift
Close #356 
This commit fixes a problem in which queries against tags would work on .inMemory stores but not on .onDisk stores.
The underlying problem was that CoreData serializes arrays of tags to binary when they are saved to disk, and predicates do no evaluate properly against binary blobs. .inMemory stores do not serialize anything, so predicates do work as one would expect.
The solution was to perform filtering against tags at the CareKitStore level instead of the CoreData level. This solution is sub-optimal from a performance perspective, but will likely never manifest as a problem given the number of tasks in a typical CareKit app.
We considered addressing the root problem by changing the tags from an array of strings into a many-to-many relationship with its own table. However, …
> Fix query by tag bug

- .travis.yml
- CareKitStore/CareKitStore/CoreData/OCKCDVersionedObject.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Contacts.swift
The problem was that a previous commit (hash 72625cb92f3c58f86c48bbb7317296faf2c1f568) incorrectly modified the header predicate such that it was no longer checking if a "next" version exists.
The solution was to rectify the predicate.
Close #357.
> Fixed query regression

- CareKit/CareKit/Synchronized View Controllers/Task/Controllers/OCKTaskController.swift
- CareKit/CareKit/Synchronized View Controllers/Task/View Controllers/OCKTaskViewController.swift
- CareKitStore/CareKitStore/Protocols/Events/OCKEventStore.swift
- CareKitStore/CareKitStoreTests/TestStoreProtocolExtensions.swift
Close #367 
Resolves an issue in which the events for tasks with many versions were not correctly returned from queries.
- Address a logic error in the store's recursive event fetch method. When fetching events from old versions of a task, the query start date was being set to a date that was later than the query applied at the beginning of the recursion. This resulted in invalid date ranges when recursing back more than one task version.
- Ensure task view controllers update when their watched task changes
- Fix a problem in which `fetchEvent(task:occurrence:)` would fail if the outcome for the event was nil.
> Resolve task version chain bug

- CareKit/CareKit.xcodeproj/project.pbxproj
- CareKit/CareKit/Lists/View/OCKListView.swift
- CareKit/CareKitTests/TestListView.swift
This fixes an issue where the background color in the `OCKListView` was not being set correctly from the view's style.
> Propagate background color in `OCKListView`

- CareKit/CareKit.xcodeproj/project.pbxproj
CareKit is no longer an umbrella framework that embeds both CareKitUI and CareKitStore.
Note: If you have installed CareKit by embedding the framework, make sure that your app embeds CareKit, CareKitUI, and CareKitStore.
> Fix umbrella framework

- CareKitStore/CareKitStore/Structs/OCKScheduleElement.swift
- CareKitStore/CareKitStoreTests/Structs/TestScheduleElement.swift
This fixes a bug that caused an error to be thrown when attempting to deserialize `OCKScheduleElement`s.
> Fix bug in deserialization of OCKScheduleElement

- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataTaskStore.swift
- CareKitStore/CareKitStore/Protocols/OCKStoreProtocol+Synchronous.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Tasks.swift
This PR adds a new `addUpdateOrDeleteTasks` method onto `OCKStore`.
This new method is useful because it allows one to perform atomic batch operations.
> Add new addUpdateOrDelete tasks method onto OCKStore

- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataTaskStore.swift
- CareKitStore/CareKitStore/Protocols/Tasks/OCKTaskStore.swift
This PR includes the newly introduced `addUpdateOrDeleteTasks` method in the task store protocol to make it publicly accessible.
> Include addUpdateOrDelete in task store protocol

- README.md
It appears that this is actually inverted for what it should be.
> fix: SwiftUI logic typo

- CareKit/CareKit/Synchronized View Controllers/Task/View Controllers/OCKTaskViewController.swift
Fixes a crash on iPad and MacOS devices because the action sheet isn't anchored. The crash occurs when you use OCKButtonLogTaskViewController and you try to tap to delete an already saved outcome.
This addresses #358.
I know that @erik-apple mentioned that iPad isn't officially supported, but I wanted to provide this fix as it's the only bug I found on the iPad so far and everything else has been working when using CareKit in my iPad app.
> Anchor action sheet in TaskViewController

- .travis.yml
- CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Contacts.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift
- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataStoreProtocol.swift
- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataTaskStore.swift
- CareKitStore/CareKitStore/Structs/OCKOutcome.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKOutcomeQuery.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+CarePlans.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Contacts.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Outcomes.swift
- CareKitStore/CareKitStoreTests/Utils.swift
- Fix #432 
- Fix #433
- Fix query by uuids for OCKContact
- Fix query by patient uuids for OCKCarePlan
- Slight change to mapping ids and uuids in OCKCoreDataStoreProtocol.swift so that CareKit can still compile on < Xcode 11.4.0
- Downgrade travis to xcode11.3 and iOS13.3 since xcode11.4 is having issues, see [this](https://github.com/carekit-apple/CareKit/pull/435#issuecomment-632079613) for details.
> Query by uuid for Outcome and expose deletedDate

- CareKitStore/CareKitStore/CoreData/OCKStore+CarePlans.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Contacts.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Patients.swift
- CareKitStore/CareKitStore/CoreData/OCKStore+Tasks.swift
- CareKitStore/CareKitStore/CoreData/OCKStore.swift
- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataTaskStore.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKCarePlanQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKContactQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKEntityQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKOutcomeQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKPatientQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKTaskQuery.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+CarePlans.swift
- CareKitStore/CareKitStoreTests/Structs/TestCarePlanQuery.swift
- CareKitStore/CareKitStoreTests/Structs/TestContactQuery.swift
- CareKitStore/CareKitStoreTests/Structs/TestOutcomeQuery.swift
- CareKitStore/CareKitStoreTests/Structs/TestPatientQuery.swift
- CareKitStore/CareKitStoreTests/Structs/TestTaskQuery.swift
This PR makes it possible to query objects where properties are `nil`.
This is useful for returning, for example, all tasks that don't have a `groupIdentifier` or all outcomes for which the `remoteID` is not set.
This feature was proposed by @cbaker6 in #418.
> Allow queries that match against nil

- CareKitStore/CareKitStore/CoreData/OCKStore+Tasks.swift
- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataTaskStore.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Outcomes.swift
This closes out #439.
OCKOutcomeValue's kind property was being persisted, but was not being populated onto structs when rehydrated from CoreData.
> Fix OCKOutcomeValue kind bug

- CareKitUI/CareKitUI/Components/Charts/OCKCartesianChartView.swift
This patch ensures that the graph area in `OCKCartesianChartView` grows first when the view is constrained to a size greater than its intrinsic content height.
> Ensure that the graph area grows before the legend when stretched

- CareKit/CareKit/Extensions/OCKContact+Extensions.swift
This PR addresses a bug reported in #451.
The label was being used for both the label and the value.
> Fix bug in which the label was used as the value for phone numbers.

- .travis.yml
- CKWorkspace.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CareKit/CareKitTests/Task/TestTaskController.swift
- CareKitFHIR/CareKitFHIR.xcodeproj/project.pbxproj
- OCKCatalog/OCKCatalog.xcodeproj/xcshareddata/xcschemes/OCKWatchCatalog.xcscheme
- Package.resolved
- Package.swift
It looks like there will be random timeouts from time-to-time due to the resources on travis and probably the time of day. If any of the timeouts become consistent, you can probably increase the wait time on the respective test.
I bumped  `testFetchWithTaskIDsReceivesDeletedTaskNotifications` by a second because it failed once, but I don't think this is a consistent failure. I did it to re-trigger the test.
It should run 5/6 of these concurrently, it's possible the travis settings for the repo is limiting the concurrent builds to 2 (or travis limits the builds for Xcode 12). Since there are more schemes in the updated version, setting the "build latest commit" setting can help canceling builds with updates to PRs
> Update travis to xcode12

- CareKitUI/CareKitUI/iOS/Contact/OCKAddressButton.swift
- CareKitUI/CareKitUI/iOS/Contact/OCKDetailedContactView.swift
- CareKitUI/CareKitUI/iOS/Controls/OCKLabeledButton.swift
- CareKitUI/CareKitUI/iOS/Task/OCKButtonLogTaskView.swift
- CareKitUI/CareKitUI/iOS/Task/OCKChecklistTaskView.swift
- CareKitUI/CareKitUI/iOS/Task/OCKGridTaskView.swift
- CareKitUI/CareKitUI/iOS/Task/OCKInstructionsTaskView.swift
- CareKitUI/CareKitUI/iOS/Task/OCKSimpleTaskView.swift
- CareKitUI/CareKitUI/iOS/Views/OCKHeaderView.swift
This fixes an issue that caused long strings in the title label of the OCKSimpleTaskView to get cutoff.
> Fix title label wrapping in OCKSimpleTaskView

- .github/workflows/swift.yml
- CareKitStore/CareKitStore/Structs/OCKOutcomeValue.swift
Hi @erik-apple, I wanted to check to see if there's a reason the `groupIdentifier` key is `group` in OCKOutcomeValue?
I was doing some encoding/decoding and ran into an issue where this came up. Though I think I can fix it in my code. Wanted to see if there was something I'm missing?
> Coding key for OCKOutcomeValue

- CareKit/CareKit/iOS/Higher Order/ViewController/OCKContactsListViewController.swift
Currently, the `OCKContactsListViewController` queries and shows all versions (even deleted ones) of contacts. Passing in date makes it only show active versions.
This is related to [version section](https://github.com/carekit-apple/CareKit#store-) of the README.
This bug was discovered by a @ChrisGambrell, an undergraduate in my iOS App Development course.
Fix #523
> Only display current version of contacts

- CareKitStore/CareKitStore/Structs/OCKScheduleElement.swift
- CareKitStore/CareKitStoreTests/Structs/TestScheduleElement.swift
This fixes a bug (#537) that would occur when generating events for an all day schedule element. If generating events for a date range that started several days after the schedule element's start date, and if the schedule element were an all day event, then events would be incorrectly returned starting from the the element's start date up to the query's start date.
> Fix a bug where all day schedule elements returned the wrong events

- CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataStoreProtocol.swift
- Package.swift
This makes it work when importing using a Package.swift file below:
```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription
let package = Package(
name: "ParseCareKit",
platforms: [.iOS(.v13), .watchOS(.v6), .macOS(.v10_13), .tvOS(.v11)],
products: [
.library(
name: "ParseCareKit",
targets: ["ParseCareKit"])
],
dependencies: [
// Dependencies declare other packages that this package depends on.
.package(name: "CareKit", url: "https://github.com/cbaker6/CareKit.git",
.revision("d4fca9a3a61d8d3fb693329254a138613dbb9837")),
.package(name: "ParseSwift", url: "https://github.com/parse-community/Parse-Swift", from: "1.1.2")
],
targets: [
.target(
name: "ParseCareKit",
dependencies: …
```
> Update Package.swift file

- CareKitStore/CareKitStore/CoreData/OCKCDHealthKitLinkage.swift
- CareKitStore/CareKitStore/CoreData/OCKCDHealthKitTask.swift
- CareKitStore/CareKitStore/CoreData/OCKCDPostalAddress.swift
The inits for `OCKCDHealKitLinkage`, `OCKCDHealthKitTask`, and `OCKCDPostalAddress` are causing app crashes. The other entities seem to be calling self instead of super, so I switched these to self and didn't see crashes anymore.
Fix #554
> Fix OCKStore inits

- CareKitStore/CareKitStore/CoreData/OCKCDOutcome.swift
This code is leftover from the #553 updates and isn't being used by anything.
> Cleaning up leftover code

- CareKitStore/CareKitStore/CoreData/OCKStore+Outcomes.swift
- CareKitStore/CareKitStoreTests/OCKStore/TestStore+Outcomes.swift
This PR is a proposed fix for #558.
When a date interval is specified on an outcome query, only one version of the outcome should be returned. Previously we were returning several, in error.
> Only return one version of an outcome when a date interval is given

- CareKitUI/CareKitUI/Shared/Localization/OCKLocalization.swift
Accessing localized resources, if integrated using Swift Package Manager, [requires using Bundle.module](https://developer.apple.com/documentation/swift_packages/localizing_package_resources):
```swift
let localizedString = NSLocalizedString(”a_localized_string”, bundle: Bundle.module, comment: “a comment”).
```
This pull request fixes this issue in CareKitUI.
> Fix localization look up through SPM

- CareKitStore/CareKitStore/HealthKit/OCKHealthKitTask.swift
The documentation is wrong here in OCKHealthKitTask.swift
It instantiates a new OCKHealthKitTask.
> Fixed instance of 'OCKCarePlan' where it should be 'OCKHealthKitTask'

- CareKitStore/CareKitStore/Structs/OCKTask.swift
The documentation is wrong here in OCKTask.swift
Fixed instance of 'OCKCarePlan' where it should be 'OCKTask'
Corrected id and title parameter description.
Removed healthKitLinkage since it does not belong to the initialization.
> Corrected OCKTask documentation

- CareKit/CareKit.xcodeproj/project.pbxproj
- CareKit/CareKit/Shared/Extensions/UIImage+Asset.swift
- CareKit/CareKit/Shared/Task/Controller/OCKTaskController.swift
- CareKit/CareKit/iOS/Utilities/OCKContactUtility.swift
- CareKit/CareKit/iOS/View Updaters/OCKHeaderView+Updatable.swift
- CareKitStore/CareKitStore/Protocols/Tasks/OCKAnyTask.swift
- OCKCatalog/OCKCatalog/Extensions/OCKStore+Extensions.swift
- OCKSample/OCKSample/AppDelegate.swift
If a card is displaying an `OCKAnyTask` it will automatically display the asset tied to the task when details are tapped. Close #524 
@erik-apple and @gavirawson-apple I couldn't find testcases where I should add tests for this. Let me know where to look and I can add them if needed
> Use asset when available in detail card view

- .github/workflows/swift.yml
Xcode 12.4 is the latest publicly available in Actions. It looks like the CI has been running agains 12.0 for awhile. Current software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210801.1/images/macos/macos-10.15-Readme.md
This will need to be bumped manually from time-to-time because of the discussion here: https://github.com/carekit-apple/CareKit/pull/492#issuecomment-675167708
Maybe this gets rid of CI failures since it's not running on older Xcode? Or at least make them less frequent.
> Bump CI to Xcode 12.4

- .github/workflows/swift.yml
- CareKitStore/CareKitStore/Protocols/CarePlans/OCKAnyCarePlanStore.swift
- CareKitStore/CareKitStore/Protocols/CarePlans/OCKCarePlanStore.swift
- CareKitStore/CareKitStore/Protocols/Contacts/OCKAnyContactStore.swift
- CareKitStore/CareKitStore/Protocols/Contacts/OCKContactStore.swift
- CareKitStore/CareKitStore/Protocols/Events/OCKAnyEventStore.swift
- CareKitStore/CareKitStore/Protocols/Events/OCKEventStore.swift
- CareKitStore/CareKitStore/Protocols/Outcomes/OCKAnyOutcomeStore.swift
- CareKitStore/CareKitStore/Protocols/Outcomes/OCKOutcomeStore.swift
- CareKitStore/CareKitStore/Protocols/Patients/OCKAnyPatientStore.swift
- CareKitStore/CareKitStore/Protocols/Patients/OCKPatientStore.swift
- CareKitStore/CareKitStore/Protocols/Tasks/OCKAnyTaskStore.swift
- CareKitStore/CareKitStore/Protocols/Tasks/OCKTaskStore.swift
I have added async/await extensions to all constituent protocols of OCKStoreProtocol and fixed miscellaneous documentation typos in those protocols.
These changes compile cleanly with Xcode 13 beta 4 and do run on iOS 15 simulator. However I haven't tested every method, nor have I committed any of my unit tests. If anyone feels unit tests are needed, please comment.
> Async/Await extensions for OCKStoreProtocol Constituents

- .github/workflows/swift.yml
- CareKitStore/CareKitStore/Protocols/CarePlans/OCKAnyCarePlanStore.swift
- CareKitStore/CareKitStore/Protocols/CarePlans/OCKCarePlanStore.swift
- CareKitStore/CareKitStore/Protocols/Contacts/OCKAnyContactStore.swift
- CareKitStore/CareKitStore/Protocols/Contacts/OCKContactStore.swift
- CareKitStore/CareKitStore/Protocols/Events/OCKAnyEventStore.swift
- CareKitStore/CareKitStore/Protocols/Events/OCKEventStore.swift
- CareKitStore/CareKitStore/Protocols/Outcomes/OCKAnyOutcomeStore.swift
- CareKitStore/CareKitStore/Protocols/Outcomes/OCKOutcomeStore.swift
- CareKitStore/CareKitStore/Protocols/Patients/OCKAnyPatientStore.swift
- CareKitStore/CareKitStore/Protocols/Patients/OCKPatientStore.swift
- CareKitStore/CareKitStore/Protocols/Tasks/OCKAnyTaskStore.swift
- CareKitStore/CareKitStore/Protocols/Tasks/OCKTaskStore.swift
https://github.com/carekit-apple/CareKit/issues/619
Updated source and workflow script.
> Removed "#if swift(>=5.5)" now that Xcode 13 is supported by CI.

- CareKit/CareKit/iOS/Contact/View Controllers/OCKContactViewController.swift
- CareKit/CareKit/iOS/Extensions/UIViewController+Extensions.swift
- CareKit/CareKit/iOS/Task/View Controllers/OCKSurveyTaskViewController.swift
- CareKit/CareKit/iOS/Task/View Controllers/OCKTaskViewController.swift
When an app is using the SwiftUI lifecycle (`App` protocol) and doesn't use the scene delegate, the `tintColor` isn't properly inherited in `surveyViewController` in `OCKSurveyTaskViewController` from the calling view. This occurs with the latest commit on the main of CareKit and the latest commit on the main of ResearchKit (https://github.com/ResearchKit/ResearchKit/commit/a89059f5dc2a91f36785b184f914b5e5fdb05877)
The fix is to set the `tintColor` directly when setting up the ResearchKit task. This works for the most part with the exception of the ResearchKit `Done` button and some others (selecting a survey option) still don't inherit the color from the calling view. I believe the button issue is a ResearchKit issue and not a CareKit issue. When the ResearchKit `Done` button is disabled …
> fix survey, contact, and task view tint colors

- .spi.yml
Avoid publishing the CareKitFHIR documentation to Swift Package Index until the DocC catalog is polished.
> Fix: Don’t deploy CareKitFHIR documentation to Swift Package Index

- CareKit/CareKit/iOS/Task/View Controllers/OCKSurveyTaskViewController.swift
Some minor changes are required to support RK 3.0. 
- https://github.com/carekit-apple/CareKit/pull/711/commits/c9ab6388ce592896c74275cae830654b6035804e Supports both old and new RK, but has redundant code
- https://github.com/carekit-apple/CareKit/pull/711/commits/d1a87996001487789f13cdc3d9bd68101f5a8b28 These changes will make CK not compatible with older versions of RK and doesn't have redundant code
I've left the current commit with the redundant code, but have tested both. The former works with old/new versions of RK. The second only works with new versions of RK
> feat: Update OCKSurveyTaskViewController to support ResearchKit 3.0

- .github/workflows/swift.yml
- CareKitStore/CareKitStore/TaskProgress/AggregatedCareTaskProgress.swift
- CareKitStore/CareKitStore/TaskProgress/BinaryCareTaskProgress.swift
- CareKitStore/CareKitStore/TaskProgress/LinearCareTaskProgress.swift
- CareKitStore/CareKitStoreTests/TaskProgress/TestAggregatedCareTaskProgress.swift
- CareKitStore/CareKitStoreTests/TaskProgress/TestBinaryCareTaskProgress.swift
- CareKitStore/CareKitStoreTests/TaskProgress/TestLinearCareTaskProgress.swift
Making the initializer public allows developers create linear progress, similar to https://github.com/carekit-apple/CareKit/blob/be7749c23c0601a81d5aaf5d169b51b1d1e4b80b/CareKitStore/CareKitStore/TaskProgress/AggregatedCareTaskProgress.swift#L96-L110
> feat: Allow developers to create instances of LinearCareTaskProgress and BinaryCareTaskProgress

- CareKitStore/CareKitStore/CoreData/Synchronization/OCKStore+Synchronization.swift
- CareKitStore/CareKitStore/Streaming/CoreDataQueryMonitor.swift
> fix: App crash when faults are not realized on CoreData objects

- CareKitStore/CareKitStore/HealthKit/OCKHealthKitPassthroughStore+EventUtilities.swift
- CareKitStore/CareKitStore/Streaming/HealthKitQueryMonitor.swift
The HealthKit store doesn't like being queried when there are no descriptors (no Care Events). When querying when there's no descriptors, this will automatically cause the app crash below:
```bash
*** Terminating app due to uncaught exception 'HKQueryValidationFailureException', reason: 'HKAnchoredObjectQuery data type must be non-nil'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001804b757c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x000000018008eda8 objc_exception_throw + 72
2   CoreFoundation                      0x00000001804b748c -[NSException initWithCoder:] + 0
3   HealthKit                           0x000000019d5302c0 -[HKAnchoredObjectQuery queue_validate] + 164
4   HealthKit                           0x000000019d51afe4 …
```
> fix: HealthKit store crash when querying objects with zero descriptors

- CareKitStore/CareKitStore/StoreCoordinator/OCKPersistentStoreCoordinator+Outcomes.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKCarePlanQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKContactQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKPatientQuery.swift
- CareKitStore/CareKitStore/Structs/Queries/OCKTaskQuery.swift
The framework crashes when you stream using: `OCKOutcomeQuery`, `OCKCarePlanQuery`, `OCKContactQuery`, `OCKPatientQuery`, `OCKTaskQuery`. Most likely happens with a standard fetch as well, but I didn't test those...
Resulting in:
This can be replicated by using a simple streaming query within a view:
```swift
// A view that has the CareStore in it's environment 
struct SimpleCareView: View {
@CareStoreFetchRequest(query: query()) private var outcomes
var body: some View {
// I want to display outcomes...
}
// Simple query
static func query() -> OCKOutcomeQuery {
OCKOutcomeQuery(for: Date())
}
}
```
This most likely results from `NSSortDescriptor` not liking keyPaths of value types and prefers reference types (I'm guessing as I'm seen some other issues in the past with value type keyPaths …
> fix: KeyPath crash when querying CareStore

- CareKitStore/CareKitStore/HealthKit/OCKHealthKitStore+Outcomes.swift
> fix: HealthStore deleteOutcomes should return on success
