CareKit.xcodeproj/project.pbxproj
Sample/OCKSample.xcodeproj/project.pbxproj
testing/OCKTest/OCKTest.xcodeproj/project.pbxproj

This would help people who are using 2 space indentation by default.

Set indentation level on project files

---

README.md

Added a colon where it was necessary to match the styling of the following paragraph

Added colon

---

CareKit/CareCard/OCKHeartView.m

Fixes lag detailed by issue #7.
Also removes unnecessary recreation of views on tintColorDidChange.

Improvements to OCKHeartView

---

CareKit/Connect/OCKConnectDetailViewController.m
CareKit/Connect/OCKConnectTableViewCell.m
CareKit/Connect/OCKContactInfoTableViewCell.m
CareKit/Connect/OCKContactSharingTableViewCell.m
CareKit/Insights/OCKGroupedBarChartView.m
CareKit/SymptomTracker/OCKRingView.m
Sample/OCKSample/Base.lproj/LaunchScreen.storyboard

Some small improvements to usability and visuals. See commit comments for further detail.
Since these were rather small I didn't feel they merited an issue, but happy to open one if that's preferred.

Small UI Improvements

---

Sample/OCKSample.xcodeproj/project.pbxproj
Sample/OCKSample/RootViewController.swift

Added popoverPresentationController sourceView to fix iPad Crash for activity ViewController Presentation

Fixed iPad crash issue for RootViewController

---

CareKit/Connect/OCKConnectDetailViewController.m

Resolve: https://github.com/carekit-apple/CareKit/issues/39

Allow phone numbers of any format

---

CareKit/Insights/OCKGroupedBarChartView.m
CareKit/Insights/OCKInsightsChartTableViewCell.m
CareKit/Insights/OCKInsightsMessageTableViewCell.m
CareKit/Insights/OCKInsightsTableViewHeaderView.m
CareKit/Insights/OCKInsightsViewController.m
CareKit/PDF/OCKDocument.m

Made some improvements to the rendering speed of the insight view cells by reducing the amount of blended layers in the cells.
See before and after. These screenshots are with the "Color Blended Layers" setting enabled in the iOS Simulator.

Various UI Performance Enhancements

---

CareKit/CareCard/OCKCareCardTableViewCell.m

Trying to address https://github.com/carekit-apple/CareKit/issues/84

Set the accessibility value as part of the OCKCareCardTableViewCell's accessibility elements

---

CareKit/CareCard/OCKCareCardTableViewHeader.h
CareKit/CareCard/OCKCareCardTableViewHeader.m
CareKit/CareCard/OCKCareCardViewController.m
CareKit/Connect/OCKConnectDetailViewController.m
CareKit/Connect/OCKConnectViewController.h
CareKit/Connect/OCKConnectViewController.m
Sample/OCKSample/RootViewController.swift
testing/OCKTest/OCKTest/ConnectTableViewController.swift

Reverts carekit-apple/CareKit#78

Revert "Add 3D Touch to Care Card and Connect"

---

CareKit/CareCard/OCKCareCardTableViewHeader.h
CareKit/CareCard/OCKCareCardTableViewHeader.m
CareKit/CareCard/OCKCareCardViewController.m
CareKit/Connect/OCKConnectDetailViewController.m
CareKit/Connect/OCKConnectViewController.h
CareKit/Connect/OCKConnectViewController.m
Sample/OCKSample/RootViewController.swift
testing/OCKTest/OCKTest/ConnectTableViewController.swift

Reverts carekit-apple/CareKit#104

Revert "Revert "Add 3D Touch to Care Card and Connect""

---

CareKit/CareCard/OCKCareCardViewController.m
CareKit/Connect/OCKConnectViewController.m

Add 3D Touch to Care Card and Connect

---

CareKit/CareCard/OCKCareCardTableViewCell.h
CareKit/CareCard/OCKCareCardTableViewCell.m

Add OCK prefix to CareCardAccessibilityElement

---

CareKit/CarePlan/OCKCarePlanStore.m

Fix for issue 175: "OCKCarePlanStore - Unwired property (directoryURL)".

---

CareKit/CarePlan/OCKCarePlanStore.m

See details in the issue #167 .

Fix for issue 167: "OCKCarePlanStore - Bug in evaluation of adherence thresholds.

---

CareKit/CareCard/OCKCareCardViewController.m
CareKit/CareContents/OCKCareContentsViewController.m
CareKit/SymptomTracker/OCKSymptomTrackerViewController.m

showToday Bug Fix

---

Sample/OCKSample/WatchConnectivityManager.swift

See #190 
Update to `WCSession.default` to `WCSession.default()`

Close #190

---

CareKit/PDF/OCKDocument.h
CareKit/PDF/OCKDocument.m

This lets you add a page break between your elements that you add to OCKDocument

Added OCKDocumentElementBreak for OCKDocument

---

CareKit/Connect/OCKConnectHeaderView.m
CareKit/Connect/OCKConnectViewController.m

Replacement for previous PR, synced with current CareKit repo and w/o dependency.

Update connect header when OCKPatient is set

---

CareKit/CarePlan/OCKCarePlanActivity.h
CareKit/CarePlan/OCKCarePlanEvent.h
CareKit/CarePlan/OCKCarePlanThreshold.h

Found some typos while reading the docs.

Found some typos while reading the docs.

---

CareKit/CareKit/Synchronized View Controllers/Calendar/OCKCalendarPageViewController.swift
CareKitUI/CareKitUI/Components/Calendar/OCKCalendarWeekView.swift

This resolves issue #277 in which programmatically setting the displayed date of the week calendar view could cause an infinite recursion in some locales.
The underlying issue was the way in which the beginning of the week was being calculated. The solution was to use a different method for determining the week in which a date falls.

Resolve locale bug

---

CareKit/CareKit/Synchronized View Controllers/Calendar/OCKCalendarPageViewController.swift
OCKCatalog/OCKCatalog.xcodeproj/project.pbxproj
OCKCatalog/OCKCatalog/ContainerViewController.swift
OCKCatalog/OCKCatalog/RootViewController.swift
OCKSample/OCKSample.xcodeproj/project.pbxproj
Package.swift

This PR is part 3/3 (#282) of the SPM adoption proposal (#271).
It adds a `Package.swift` file and updates both OCKSample and OCKCatalog apps to rely on the new package.

Integrate SPM

---

CareKit/CareKit/Lists/Controller/OCKDailyPageViewController.swift
CareKit/CareKit/Synchronized View Controllers/Calendar/OCKCalendarPageViewController.swift
CareKit/CareKit/Synchronized View Controllers/Task/OCKSimpleTaskViewController.swift
CareKitStore/CareKitStore/Structs/OCKTask.swift
CareKitStore/CareKitStore/Structs/OCKTaskQuery.swift
CareKitStore/CareKitStoreTests/TestStoreProtocolExtensions.swift
CareKitUI/CareKitUI/Components/Calendar/OCKCalendarWeekView.swift
OCKSample/OCKSample/AppDelegate.swift
OCKSample/OCKSample/CareViewController.swift

* New OCKTaskQuery property to exclude tasks that do not have active events in the queried time interval.
* Sample app demonstrates better example of displaying tasks. 
* TipView in sample app only appears on current day. 
* Bug fixes related to week page scrolling and other UI issues.

Feature & Sample App Improvements; Bug Fixes

---

CareKitUI/CareKitUI/Common/Buttons/OCKButton.swift

Just a tiny coding style change, I thought it felt more natural 😌

Use toggle() method

---

CareKit/CareKit/Synchronized View Controllers/Task/OCKSimpleLogTaskViewController.swift

fix the header view's detail disclosure for the simple log task view

add detail disclosure to simple log view

---

OCKSample/OCKSample.xcodeproj/project.pbxproj

FIX 318: Link against embedded frameworks in OCKSample app

---

README.md

Thank you for making this awesome framework! I should have caught this and added it to the other PR. I think this will be the last typo fix for a bit.

Change XCode to Xcode

---

CareKit.xctestplan
CareKit/CareKit/Synchronized View Controllers/Chart/Synchronizers/OCKCartesianChartViewSynchronizer.swift

This change addresses a date selection bug that affected certain locales, including Germany.
It also adds unit test passes in several new regions to ensure that this bug does not regress.

Date selection bug fix

---

CareKitStore/CareKitStore.xcodeproj/project.pbxproj
CareKitStore/CareKitStore/CoreData/OCKStore.swift
CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataStoreProtocol.swift
CareKitStore/CareKitStoreTests/OCKStore/TestStore.swift

This PR adds a method for deleting instances of `OCKStore`.
Close #378

Add method for deleting an OCKStore

---

CareKit/CareKit.xcodeproj/project.pbxproj
CareKit/CareKit/Synchronized View Controllers/Calendar/View Controllers/OCKCalendarViewController.swift
CareKit/CareKit/Synchronized View Controllers/Chart/View Controllers/OCKChartViewController.swift
CareKit/CareKit/Synchronized View Controllers/Contact/View Controllers/OCKContactViewController.swift
CareKit/CareKit/Synchronized View Controllers/Task/View Controllers/OCKTaskViewController.swift

This update fixes a memory leak that affected all synchronized view controllers.

Memory leak fix

---

CareKitStore/CareKitStore/Structs/OCKPostalAddress.swift
CareKitStore/CareKitStoreTests/Structs/TestContact.swift

Fixes an issue in which the address field on OCKContact was not being serialized.

Fix address serialization

---

CareKitStore/CareKitStore/Structs/OCKSchedule.swift
CareKitStore/CareKitStoreTests/Structs/TestSchedule.swift

This is a fix for the bug discovered in #405.

Fix weekly schedule start date

---

CareKit/CareKit/Lists/Controller/OCKDailyPageViewController.swift

Fixes a bug where the animated flag in OCKDailyPageViewController's `selectDate(_:animated:)` wasn't passed properly.

Fix animation bug

---

OCKCatalog/OCKCatalog/OCKStore+Extensions.swift

Fix build errors in OCKCatalog.

Fix build errors

---

CareKitUI/CareKitUI/Components/Charts/Layers/OCKGridLayer.swift
CareKitUI/CareKitUI/Components/Charts/OCKCartesianGraphView.swift
CareKitUI/CareKitUI/Components/Charts/OCKGridView.swift

This change makes it possible to set a number formatter that will be used by the chart to format vertical axis values.

Expose a number formatter for chart axes

---

CareKitUI/CareKitUI/Components/Charts/Layers/OCKGridLayer.swift

This PR is an enhancement that adds a bottom axis label whenever the axis does not start from 0.

Add bottom axis label

---

CareKitUI/CareKitUI/Components/Charts/Gradient Plots/OCKGradientPlotView.swift
CareKitUI/CareKitUI/Components/Charts/OCKCartesianChartView.swift
CareKitUI/CareKitUI/Components/Charts/OCKCartesianGraphView.swift

This PR fixes a problem with breaking constraints on `OCKCartesianChartView` when it is used in table view cells.

Fix breaking constraints on OCKCartesianChartView

---

CareKitUI/CareKitUI.xcodeproj/project.pbxproj
CareKitUI/CareKitUI/Shared/Components/CircularCompletionView.swift
CareKitUI/CareKitUI/Shared/Extensions/OCKStyler+Extension.swift
CareKitUI/CareKitUI/Shared/Style/OCKAppearanceStyler.swift
CareKitUI/CareKitUI/Shared/Task/SimpleTaskView.swift
CareKitUI/CareKitUI/iOS/Controls/OCKCheckmarkButton.swift

This PR makes the border width of circular buttons across CareKit more uniform.

Make border thickness of circular buttons uniform

---

CareKit/CareKit/iOS/Higher Order/ViewController/OCKDailyPageViewController.swift

This PR adds pull-to-refresh to `OCKDailyPageViewController`. It includes one new public property and one new public method. This PR should help with #476.
```swift
open class OCKDailyPageViewController {
// ...
/// The page that is currently being displayed.
open var currentPage: OCKListViewController?
/// Reload the contents at the currently selected date.
open func reload()
// ...
}
```

Add currentPage, reload, pull-to-refresh to OCKDailyPageViewController

---

CareKitStore/CareKitStore/StoreCoordinator/OCKPersistentStoreCoordinator+Tasks.swift

This is a fix that closes #474.

Fix issue updateAnyTasks calls through to add instead of update

---

CareKitStore/CareKitStore/CoreData/OCKManagedObjectModel.swift

Note to Task relationship cardinality is 0..* and should be 0..1

Note->Task cardinality should be 0..1

---

CareKitUI/CareKitUI.xcodeproj/project.pbxproj
CareKitUI/CareKitUI/Shared/Localization/en.lproj/Localizable.strings
CareKitUI/CareKitUI/iOS/Task/Buttons/SliderLogButton.swift
CareKitUI/CareKitUI/iOS/Task/Collection/Slider.swift
CareKitUI/CareKitUI/iOS/Task/Collection/SliderStyle.swift
CareKitUI/CareKitUI/iOS/Task/SliderLogTaskView.swift
CareKitUI/CareKitUITests/Task/TestSliderLogTaskView.swift
OCKCatalog/OCKCatalog/Sections/TaskSection.swift
OCKCatalog/OCKCatalogUITests/Tests/UITestCatalogHomePage.swift

Hey @gavirawson-apple! This is a PR with only the CareKitUI files included from my Slider Log Task View PR (#479)

Add SliderLogTaskView to CareKitUI

---

CareKitStore/CareKitStore/StoreCoordinator/OCKStoreCoordinator.swift
CareKitStore/CareKitStoreTests/TestPersistentStoreCoordinator.swift

This is a proposed fix for #546

Ensure that outcome and store are both HK related

---

CareKitStore/CareKitStoreTests/OCKHealthKitStore/TestHealthKitStore+Tasks.swift
CareKitStore/CareKitStoreTests/OCKStore/TestStore+Tasks.swift

One of the tests was implemented in a way that caused it to fail at certain times of the day, but not others.

Fix fragile test

---

CareKitStore/CareKitStore/Protocols/Tasks/OCKAnyTaskStore.swift
CareKitStore/CareKitStoreTests/OCKStore/TestStore+Tasks.swift

Fix for #545

---

CareKitStore/CareKitStore/HealthKit/OCKHealthKitTask.swift

Updated title description in health kit task documentation. Forgot to update this part in #573

HealthKitTask Documentation Update

---

CareKit/CareKit/Shared/Task/Controller/OCKTaskEvents.swift
CareKitStore/CareKitStore/Protocols/Events/OCKAnyEventStore.swift
Package.swift

This PR resolves a handful of warnings in Xcode 13 beta.

Resolve build warnings in Xcode 13 beta

---

CareKitStore/CareKitStore/CoreData/OCKStore+Tasks.swift

Fix task type naming collision in Xcode 13 beta 1.

---

CareKit/CareKit/Shared/Utilities/OCKScheduleUtility.swift
CareKitUI/CareKitUI/Shared/Localization/en.lproj/Localizable.strings

Added missing language strings and replaced them in OCKScheduleUtility.

Added missing translations and language strings (#502)

---

CareKitUI/CareKitUITests/OCKResponsiveLayoutTests.swift
CareKitUI/CareKitUITests/TestColorExtension.swift
CareKitUI/CareKitUITests/TestStylableView.swift

Hi there! This is my first PR to CareKit (a very simple one) so do let me know if I've missed anything and I'll amend my changes as soon as possible.
• "unepected" → "unexpected"
• Indentations are consistent with other tests
• Other typo fixes

Consistency improvements for CareKitUITests

---

CareKitUI/CareKitUI/iOS/Task/Buttons/OCKLogItemButton.swift

Remove optionality check for non-optional value.

Optionality fix

---

.github/workflows/swift.yml
CareKitStore/CareKitStoreTests/Structs/TestOutcomeValue.swift

ci: Update CI to latest Xcode

---

CKWorkspace.xcworkspace/xcshareddata/swiftpm/Package.resolved
CareKitFHIR/CareKitFHIR.xcodeproj/project.pbxproj
Package.resolved
Package.swift

feat: Update FHIRModels dependency
